spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_ON_EXIT=FALSE

---

spring:
  profiles: local
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: admin
  jpa.hibernate.ddl-auto: create-drop